---
env:
  - ANSIBLE_VERSION=2.4
    DOCKER_COMPOSE_VERSION=1.17.0
  

dist: xenial
sudo: enabled
language: python
python: "2.7"

#addons:
#  apt:
#    update: true

branches:
  only:
    - master

services:
  - docker

before_install:
  - sudo curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi

script:
  - ansible-playbook -i tests/inventory.ini tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory.ini tests/test.yml -vvvv

