{
 "title": "Docker Host",
 "description": "Docker host metrics",
 "tags": [ "system" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "max",
   "targets": [
    { "expr": "node_time - node_boot_time" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (sum(rate(node_cpu{mode=\"idle\"}[1m])) * 100 / scalar(count(node_cpu{mode=\"user\"})))"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "node_memory_MemAvailable" }
   ]
  },
  {
   "title": "Free Swap",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "node_memory_SwapFree" }
   ]
  },
  {
   "title": "Free Storage (/)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_filesystem_avail{mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Free Storage (/data)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_filesystem_avail{mountpoint=\"/data\"}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_procs_running", "legendFormat": "running" },
    { "expr": "node_procs_blocked", "legendFormat": "blocked by I/O" }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": " irate(node_intr[5m])", "legendFormat": "interrupts" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal - node_memory_MemAvailable",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_MemAvailable", "legendFormat": "Available" }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_bytes_read[10m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_bytes_written[10m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_ms[10m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapTotal - node_memory_SwapFree",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_SwapFree", "legendFormat": "Free" }
   ]
  },
  {
   "title": "Swap I/O",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin[1m]) * 4096 or irate(node_vmstat_pswpin[5m]) * 4096",
     "legendFormat": "In"
    },
    {
     "expr": "rate(node_vmstat_pswpout[1m]) * 4096 or irate(node_vmstat_pswpout[5m]) * 4096",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Load Average 1/5/15 m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1 / scalar(machine_cpu_cores)",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5 / scalar(machine_cpu_cores)",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15 / scalar(machine_cpu_cores)",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{device!=\"lo\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_bytes{device!=\"lo\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "Disk Usage (/)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail{mountpoint=\"/\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_filesystem_size{mountpoint=\"/\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Disk Usage (/data)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail{mountpoint=\"/data\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_filesystem_size{mountpoint=\"/data\"}",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}