{
 "title": "MacOS VMs System Metrics",
 "description": "System metrics from metricbeat to elasticsearch",
 "tags": [ "macos" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "vm",
    "query": "{\"find\": \"terms\", \"field\": \"beat.hostname\"}"
   },
   {
    "name": "hypervisor",
    "query": "{\"find\": \"terms\", \"field\": \"hypervisor\", \"query\": \"beat.hostname:$vm\"}"
   },
   { "name": "adhoc" }
  ]
 },
 "panels": [
  { "title": "CPU, RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "beat.hostname",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.cpu.total.norm.pct",
       "id": "3",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "hypervisor:$hypervisor AND beat.hostname:$vm AND metricset.module:system AND metricset.name:cpu",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1076",
       "fake": true,
       "field": "beat.hostname",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1010",
       "field": "vm_ip",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1000",
       "field": "system.uptime.duration.ms",
       "id": "1",
       "inlineScript": "_value / 1000",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": { "script": { "inline": "_value / 1000" } },
       "type": "max"
      },
      {
       "$$hashKey": "object:1001",
       "field": "system.filesystem.used.pct",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:1002",
       "field": "system.filesystem.used.bytes",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:1003",
       "field": "system.filesystem.total",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "$$hashKey": "object:1004",
       "field": "system.process.summary.total",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "hypervisor:$hypervisor AND beat.hostname:$vm AND metricset.module:system",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "beat.hostname",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.memory.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "hypervisor:$hypervisor AND beat.hostname:$vm AND metricset.module:system AND metricset.name:memory",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "beat.hostname",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.memory.swap.used.bytes",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "hypervisor:$hypervisor AND beat.hostname:$vm AND metricset.module:system",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "RAM (actual used)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "beat.hostname",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "system.memory.actual.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "hypervisor:$hypervisor AND beat.hostname:$vm AND metricset.module:system AND metricset.name:memory",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "beat.hostname",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "system.filesystem.used.pct",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "hypervisor:$hypervisor AND beat.hostname:$vm AND metricset.module:system",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}